Add webhook template export
theforeman/hammer-cli-foreman-webhooks pull request #3
Opened 2022-03-20 11:23 UTC by adiabramovitch

2022-03-20 13:39 UTC, adiabramovitch commented
@ofedoren Found something weird and can use your help/opinion: 
 It seems like there is a problem with the loading of the webhook plugin and the resource = nil:
 
![image](https://user-images.githubusercontent.com/57755873/159160969-201e8605-0b55-4ea9-82fc-831f43685d00.png)

I initially thought it has something to do with my PR but I think that it is something else, I can't rake apipie:cache - it failed and I can't see webhook in apidoc. 

Do you see the same problem?

2022-03-23 14:32 UTC, ofedoren commented on lib/hammer_cli_foreman_webhooks/webhook_template.rb
> +      desc _('Export a webhook template to ERB')
This can be omitted since the description will be fetched from API cache.

2022-03-23 14:32 UTC, ofedoren commented on lib/hammer_cli_foreman_webhooks/webhook_template.rb
> +      def msg
I guess this can wait until we finish https://github.com/theforeman/hammer-cli-foreman/pull/598 :)

2022-03-23 14:32 UTC, ofedoren commented on test/unit/webhook_template_test.rb
> +      it_should_accept 'path', ['--path=/tmp']
For some reason exactly this one tests fails... :/

2022-03-23 14:32 UTC, ofedoren commented on test/unit/webhook_template_test.rb
> +
Redundant line.

2022-03-23 14:32 UTC, ofedoren commented on test/unit/webhook_template_test.rb
> +describe HammerCLIForemanWebhooks::WebhookTemplate do
If we have `foreman_api.json` available, then it's better to use functional tests.

2022-03-23 14:33 UTC, ofedoren commented
> After commenting out this line the apidoc was generated and the problem was solved.

Well, if it makes at least some `events` available in the docs then OK. There is also a patch to webhook plugin: https://github.com/theforeman/foreman_webhooks/pull/49

2022-03-28 10:38 UTC, ofedoren reviewed
Thanks, @adiabramovitch, I guess we can now use
```ruby
def saved_response_message(filepath)
  _("The webhook template has been saved to %{path}.") % { path: filepath }
end
```

2022-03-28 10:59 UTC, ofedoren requested changes
Thanks, @adiabramovitch! Tested with https://github.com/theforeman/hammer-cli-foreman-webhooks/pull/2 and the tests seems to pass, but with some small adjustments:

2022-03-28 10:59 UTC, ofedoren commented on test/functional/webhook_template_test.rb
> +      assert_cmd(success_result("Import webhook template succeeded.\n"), result)
```suggestion
      assert_cmd(success_result("Imported webhook template successfully.\n"), result)
```

2022-03-28 10:59 UTC, ofedoren commented on test/functional/webhook_template_test.rb
> +      output = OutputMatcher.new("The webhook template has been saved to #{tempfile.path}")
This actually needs https://github.com/theforeman/hammer-cli-foreman-webhooks/pull/3#pullrequestreview-922945239

2022-03-28 10:59 UTC, ofedoren commented on test/functional/webhook_template_test.rb
> +  describe 'import' do
:heart:

2022-03-28 10:59 UTC, ofedoren commented on test/functional/webhook_template_test.rb
> +        'Could not import webhook template')
```suggestion
        'Could not import the webhook template')
```

2022-03-29 09:58 UTC, ofedoren approved these changes
Thanks, @adiabramovitch! Works as expected and tests are green :rose:

2022-03-29 09:58 UTC, merged